<?php

/**
 * @file
 * Primary module hooks for slac_core module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\slac_core\Entity\Event;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function slac_core_entity_bundle_info_alter(array &$bundles) {
  if (isset($bundles['node']['event'])) {
    $bundles['node']['event']['class'] = Event::class;
  }
}
