#!/bin/bash

set -eo pipefail

#
# This script deploys the build artifact to Pantheon.
# On the live branch the dev environment is used.
# On the integration and main branches, a multidev environment is used.
#

# Cut gesso gitignore at the cut mark.
cd web/themes/gesso
terminus build:gitignore:cut
cd ../../../

# Authenticate with Terminus
terminus -n auth:login --machine-token="$TERMINUS_TOKEN"

if [[ $CI_BRANCH != 'live' ]]
then
  # Create a new multidev environment (or push to an existing one)
  terminus -n build:env:create "$TERMINUS_SITE.dev" "$TERMINUS_ENV" --yes
else
  # Push to the dev environment
  terminus -n build:env:push "$TERMINUS_SITE.dev" --yes
fi

# Run Drush Deploy
terminus -n drush "$TERMINUS_SITE.$TERMINUS_ENV" -- deploy

# Clear the environment cache
terminus -n env:clear-cache $TERMINUS_SITE.$TERMINUS_ENV

# Ensure secrets are set
terminus -n secrets:set "$TERMINUS_SITE.$TERMINUS_ENV" token "${GH_TOKEN:-$GITHUB_TOKEN}" --file='.build-secrets/tokens.json' --clear --skip-if-empty
# Delete old multidev environments associated
# with a PR that has been merged or closed.
terminus -n build:env:delete:pr $TERMINUS_SITE --yes
